export enum OrderStatus {
  PENDING = 'PENDING',
  AWAITING_PAYMENT = 'AWAITING_PAYMENT',
  PAID = 'PAID',
  EXPIRED = 'EXPIRED',
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}
